### ISSUE TITLE
Use full canton name on Other cantons page

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/COVID-CH-dashboard#2]
Figures and text in the other cantos page, currently use the canton 2 letter symbol, it should instead use their full name.

**Comment by eduardocorrearaujo** [comment]
Right. I will add a dictionary to get the full name by the geoRegion name.

**Comment by eduardocorrearaujo** [comment]
Do you want the full name just in the title of the plots? If you wish to, in the select box, I can put the: full name  + (2 letter symbol), by example: Genève (GE)
