### ISSUE TITLE
Omit last point in the series 

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/COVID-CH-dashboard#9]
The last point in FOPHs series are frequently severely underreported. So we should omit it from the plot: `[:-1]`or even `[:-2]`.

We should also omit it when calculating the metrics showed above the plots (as seen on figure below).

![image](https://user-images.githubusercontent.com/140123/149501723-9f205444-d6e1-4065-89dc-5a6a8e3f02b8.png)

**Comment by eduardocorrearaujo** [comment]
Should I, too, delay the date shown in the first line, right?

**Comment by fccoelho** [comment]
Just delete the last three lines of the dataframe.
